/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotracktest_audiotrack_MusicDecoder */

#ifndef _Included_com_example_audiotracktest_audiotrack_MusicDecoder
#define _Included_com_example_audiotracktest_audiotrack_MusicDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audiotracktest_audiotrack_MusicDecoder
 * Method:    openFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotracktest_audiotrack_MusicDecoder_openFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_audiotracktest_audiotrack_MusicDecoder
 * Method:    readSamples
 * Signature: ([SI[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_audiotracktest_audiotrack_MusicDecoder_readSamples
  (JNIEnv *, jobject, jshortArray, jint, jintArray);

/*
 * Class:     com_example_audiotracktest_audiotrack_MusicDecoder
 * Method:    closeFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiotracktest_audiotrack_MusicDecoder_closeFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
