/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audiotracktest_opensles_SoundTrackController */

#ifndef _Included_com_example_audiotracktest_opensles_SoundTrackController
#define _Included_com_example_audiotracktest_opensles_SoundTrackController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audiotracktest_opensles_SoundTrackController
 * Method:    setAudioDataSource
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_audiotracktest_opensles_SoundTrackController_setAudioDataSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_audiotracktest_opensles_SoundTrackController
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiotracktest_opensles_SoundTrackController_play
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audiotracktest_opensles_SoundTrackController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audiotracktest_opensles_SoundTrackController_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
